# encoding: utf-8

source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.2'

gem 'devise', '~> 3.5.1'

# Use postgres as the database for Active Record
gem 'pg'

gem 'chat', path: "/Users/sebastianmelgar/Development/chat"

gem 'factory_girl_rails', '~> 4.5.0'
gem 'faker', '~> 1.4.3'
gem 'rspec-rails', '~> 3.3.2'
gem 'spork-rails', '~> 4.0.0'
gem 'thin', '~> 1.6.3'

gem 'database_cleaner', '~> 1.4.1'
gem 'shoulda-matchers', '~> 2.8.0'
gem 'simple_token_authentication', '~> 1.6.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
